Update cosmwasm projects
CosmWasm/cw-awesome pull request #18
Opened 2022-10-19 18:31 UTC by uint

Merge after #17

Just a small update to CosmWasm specific repos

2022-10-20 07:20 UTC, ethanfrey requested changes
Still a lot of cruft to clean up.
Left some comments.

2022-10-20 07:20 UTC, ethanfrey commented on README.md
> +- [cw20-bonding](https://github.com/CosmWasm/cosmwasm-plus/tree/master/contracts/cw20-bonding)
Wait... those aren't here at all...

We moved those into cw-tokens and they should have their own section.
I would just reference `cw-tokens` as a whole to look into as unaudited / unreviewed examples to build projects around cw20 tokens.

And just include what is still in cw-plus

2022-10-20 07:20 UTC, ethanfrey commented on README.md
> +- [name service](https://github.com/InterWasm/cw-contracts/tree/main/contracts/nameservice):
Honestly, this repo is not really maintained and not a good place for people to learn modern practices. Let's remove cw-contracts (and point to cw-tokens and cw-nfts)

2022-10-20 07:20 UTC, ethanfrey commented on README.md
> +- [substrate-light-client](https://github.com/ChorusOne/substrate-light-client):
Check if these 2 chorus one projects are still active?

We could have a "historical archive" for interesting proof of concepts that were since abandoned. Or just remove the abandoned projects.

This was written 1-2 years ago with many few projects. Let's highlight many more awesome active projects here. Things like dao-dao and mars protocol and tgrade poe-contracts as well-designed large systems to get inspiration from.

2022-10-20 07:20 UTC, ethanfrey commented on README.md
> +- [cw-multi-test](https://crates.io/crates/cw-multi-test)
Yes good to add new ones here.
But why so low? Those should go on the top, near the standard library. Definitely before all the cw1-subkeys or cw20-bonding stuff.

2022-10-20 07:20 UTC, ethanfrey commented on README.md
> +You can find the Official Confio maintained dApp instances deployed here:
These are not maintained or minimally maintained.

Please ask @pyramation and @msteiner96 for good examples for dApps we can use. I know `create-cosmos-app` is a great starter kit. Are there any examples of full-fledged working apps, we would like to present for reference?

junoswap-ui? dao-dao-ui?

I would delete this whole section now and make an issue to revisit it

2022-10-20 21:46 UTC, pyramation commented on README.md
> +You can find the Official Confio maintained dApp instances deployed here:
Good suggestions. I agree if they're not maintained let's remove them. 

Also would be great to publish an example that uses `create-cosmos-app`, for now the best we can do is link to [create-cosmos-app](https://github.com/cosmology-tech/create-cosmos-app) 

Maybe when mesh-security launches, we can use that as a reference site. Otherwise, we can publish something soon that uses a simple cw20 example.

2022-10-24 13:33 UTC, uint commented on README.md
> +- [cw20-bonding](https://github.com/CosmWasm/cosmwasm-plus/tree/master/contracts/cw20-bonding)
If we're cleaning this up, would it make sense to just have one link to `cw-plus`, list the specs that live there, and be done? That would leave more breathing space for other repos (like ones from other projects/companies).

We can focus on having detail about the specific cw-plus contracts in the cw-plus README

2022-10-24 15:20 UTC, uint commented on README.md
> +You can find the Official Confio maintained dApp instances deployed here:
Alright, I added `create-cosmos-app` to tooling. I also removed the contents of the dApp section.

Happy to continue this discussion in #19.

2022-10-24 15:30 UTC, uint commented on README.md
> +- [substrate-light-client](https://github.com/ChorusOne/substrate-light-client):
Last commit 2 years ago, but I don't know. Maybe it works and is still used? Who would I ask?

2022-10-26 09:29 UTC, ethanfrey approved these changes
Looks good. Please address the concrete comments I left (they should be cut and paste mainly), then feel free to merge

2022-10-26 09:29 UTC, ethanfrey commented on README.md
>  - [CosmWasm official documentation](https://docs.cosmwasm.com)
I would definitely include https://book.cosmwasm.com here.
And remove docs for now. It is outdated, we should add it back when it is ready

2022-10-26 09:29 UTC, ethanfrey commented on README.md
> +not use them in production:
Maybe something like this?

"Please do not use them in production as is. You are welcome to fork them, and independently review, refine and audit them, using them as a basis for your protocol. Or just as inspiration"

2022-10-26 09:29 UTC, ethanfrey commented on README.md
> +- [substrate-light-client](https://github.com/ChorusOne/substrate-light-client):
Let's remove for now. ICF has stopped funding this.
It is not maintained - it could be included in "interesting approaches", not the headliner for "These projects/contracts are developed and maintained by CosmWasm community"

2022-10-26 09:29 UTC, ethanfrey commented on README.md
> +- [CW20 Clawback](https://github.com/tomtau/hackatom): HackAtom V prototype of a
These two ones could be used, but I would prefer more maintained ones. How about putting the following examples here and then merging and we can view more examples later:

* https://github.com/DA0-DA0/dao-contracts - DAO DAO is the leading software to build your own DAO on CosmWasm chains, quickly surpassing Aragon in functionality
*  https://github.com/mars-protocol/v1-core - Delphi's "Mars Protocol" is the leading lending protocol on Terra and soon launching on Osmosis
* https://github.com/public-awesome/launchpad - Stargaze provides contracts to easily create and manage new NFT collections.

We can add more later, but I think these are all powerful examples of larger CosmWasm apps in production. Please put these three in this section and we can revisit in a future PR

2022-10-26 10:35 UTC, merged